%YAML:1.0	#注意：一定要有这行
verison: "1.0.0"
ros_enable: "false"
Debug: "false"
###################################
camera_config_path: "/home/gyxy/Desktop/workspeaseMY/success2025/cfg/hand.config"
########show on picture############
enable_show: "true"
FPS_show: "false"
time_show: "true"